name: Sync Forked Repository

on:
  schedule:
    - cron:  '50 12 * * *'  # 每天UTC 00:00触发
    

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout forked repository
      uses: actions/checkout@v3
      with:
        repository: smallfawn/v_jstools
        ref: main

    - name: Checkout upstream repository
      uses: actions/checkout@v3
      with:
        repository: cilame/v_jstools
        ref: main

    - name: Sync changes
      run: git push origin HEAD:main
